INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'rantai harus ganti baru');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'gear harus ganti baru');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'lumasi saja rantai');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'bersihkan rantai');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'kencangkan rantai');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'kendorkan rantai');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'bersihkan gear');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Saringan fuelpump kotor');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Injektor Kotor');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Busi');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Cop Busi kurang tepat');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Aki');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Pengisian tidak normal');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kiprok');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kelistrikan kabel sistem starter');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Armature Starter');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Bendik Starter');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kones ');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Bearing as roda');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Seal master rem bocor');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Minyak rem habis');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kanvas rem habis');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kanvas rem kotor');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Master rem butuh grease');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Master rem kemasukan udara');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kehabisan oli');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Ganti Oli');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kanvas kopling aus');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kompresi kurang');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Tensioner');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Rantai timing');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Throttle kotor');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Filter udara kotor');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Setel kopling');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Saluran BBM');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Kelistrikan sistem pengapian');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Brushing starter');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Gasket, paking magnet');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Coolant');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Sirkulasi Radiator');
INSERT INTO rusak (kerusakan_id,kerusakan_jenis) VALUES (NULL,'Thermostart');
